Cargo.toml
src/tty/unix.rs

The constant was just added on all targets in the latest release, so
bump to that.

Use TIOCGWINSZ from libc

---

src/lib.rs
src/pb.rs
tests/lib.rs

* Added **tick** field to prefix:
- Char field that looks like a loading symbol ; useful to show ProgressBar is still being updated even though no progress are made.
- ** speed ** field looks odd when the bar is being updated with **tick**, so best option right now is to disable it (maybe later the speed calculation could take place in _**add**_ instead of __**draw**__, so that only progress would result in speed calculation).
- Calling _pb.tick_ on a bar with 0 progress will result in a panic (_division by zero_), so be sure to have called _pb.inc()_ **at least once** before using _pb.tick()_
* Added **message** field to prefix:
- message can be changed by calling _pb.message("smthng")_
- message field will disappear when calling _pb("")_.
- message of same length should be used when …

Added message and tick fields in prefix

---

src/lib.rs
src/pb.rs

- Added support for passing an arbitrary `Write` object instead of stdout. I think It makes it more testable and I don't see why it shouldn't be possible. I needed to print to stderr, for example.
- Fixes #15
- Exposed `total` field
I need it to happen for a project of mine. I understand it might not be exactly what you want so I'm open to discussing changes or removing the PR.

Arbitrary writer + Fix #15

---

src/tty/windows.rs

The width reported on windows was off by one, which resulted in the too-long string forcing the terminal to print a new line. This pull request fixes that error.
Should close issue #17

Newlines are no longer created for every progress bar update

---

src/pb.rs

Fixes #47 
I'm not sure, why you have put `.as_ref()` here in the first place. So maybe I'm missing something.

Turn .as_ref() calls into .to_string() calls to remove type ambiguity.

---

Cargo.toml
src/tty/unix.rs

TIOCGWINSZ is defined in libc as c_int, but ioctl() expects
an c_ulong.

Fix for DragonFly and FreeBSD

---

Cargo.toml
src/tty/windows.rs

This updates the winapi crate to 0.3, which re-organizes its modules and
removes the need for kernal32-sys. More and more crates are using v0.3,
and this allows better reuse in larger dependency graphs.
The other notable change is winapi's heavy use of features to cull sub modules. This will only matter when using more winapi functions.
See `winapi`'s README for details.
> 
> ### Why am I getting errors about unresolved imports?
> 
> Each module is gated on a feature flag, so you must enable the appropriate feature to gain access to those items. For example, if you want to use something from `winapi::um::winuser` you must enable the `winuser` feature.
> 
I've been using this crate in a couple small projects, and having two winapi versions in the dependency graph very quickly handicaps …

Update winapi to 0.3

---

.travis.yml
examples/multi.rs
examples/simple.rs
src/lib.rs
src/multi.rs
src/pb.rs
src/tty/redox.rs
src/tty/unix.rs
src/tty/windows.rs
tests/lib.rs

This adds the .travis.yml file to configure travis to validate the repository. If you then go through the Travis CI setup process to link it to the PB github account, travis will automatically validate new commits and pull requests. I think this would be helpful in addressing the backlog of requests.
Also run Cargo.fmt (since the .travis.yml enforces correct formatting)

Add configuration for Travis CI

---

src/lib.rs
src/pb.rs

Closing #58
Other formatting changes caused by `cargo fmt`.

pb: better progress-bar padding

---

Cargo.toml

Exclude non-source files from crate, making it smaller

---

src/tty/mod.rs
src/tty/wasi.rs

Pbr is referenced from many crates and provides really cool reporting capabilities. Though at the moment compiling to wasm32-wasi is failing, nevertheless it provides elementary stdout capabilities. 
This PR adds wasi target support allowing to compile dependant crates, but also inheriting cursor control from unix which is most common deployment platform for terminal-like software. On other terminals it will still work, though not so nice until good tty support is added to WASI core spec, here is discussion in the past about the topic https://github.com/WebAssembly/WASI/issues/42

Add elementary wasi support

---

Cargo.toml
examples/multi.rs
examples/multi_bg.rs
src/lib.rs
src/multi.rs

Allows the creation of new progress bars while the `MultiBar` is already listening.
By wrapping a `MultiBar` in an `Arc`, it can be safely shared and used across threads.
Closes #35 
Closes #87

feat: MultiBar is now thread-safe; Create new bars dynamically

---

src/pb.rs

This allows for creating a bar, but start using it later and have the time estimations be correct.

Added reset_start_time

---

Cargo.toml
src/lib.rs
src/pb.rs

pbr currently depends on version 0.1 of time which is was found to contain a security vulnerability
(RUSTSEC-2020-0071 [1]). Updating to the current 0.3 branch would be a possiblity, however that
doesn't gain us anything over just relying on std. SteadyTime no longer exists and was never
actually steady in the first place [2]. For a while there was a fallback that turned SteadyTime
into an alias for time::Instant [3] which in turn is a wrapper around std::time::Instant adding
support for negative durations.
pbr doesn't deal with negative durations so swap time::Duration for std::time::Duration and
time::SteadyTime for std::time::Instant.
[1] https://rustsec.org/advisories/RUSTSEC-2020-0071
[2] https://github.com/time-rs/time/issues/95
[3] …

Drop dependency on `time`

---

src/lib.rs

Writer::write does NOT guarantee that all bytes in the buffer get written. Writer::write_all needs
to be used for that.
Spotted by clippy

Ensure all output gets written

---

src/pb.rs

String::replace doesn't modify the original String, so `to_owned` can be dropped. It also accepts
&[char] as a pattern and replaces any of the chars found. The two calls to `replace` can thus be
combined into one.
This brings us from three copies with two scan passes down to one copy with one scan pass.

Avoid copying the message three times in ProgressBar::message

---

README.md
examples/max_refresh_rate.rs
examples/multi.rs
examples/multi_bg.rs
examples/npm_bar.rs
examples/simple.rs
src/lib.rs
src/tty/unix.rs
src/tty/wasi.rs
src/tty/windows.rs

They have been mostly phased out with Rust 2018.

Remove `extern crate` lines

---

src/pb.rs

```
warning: constants have by default a `'static` lifetime
--> src/pb.rs:19:16
|
19 | const FORMAT: &'static str = "[=>-]";
|               -^^^^^^^---- help: consider removing `'static`: `&str`
|
= note: `#[warn(clippy::redundant_static_lifetimes)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_static_lifetimes
warning: constants have by default a `'static` lifetime
--> src/pb.rs:20:21
|
20 | const TICK_FORMAT: &'static str = "\\|/-";
|                    -^^^^^^^---- help: consider removing `'static`: `&str`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_static_lifetimes
```

Fix clippy warnings: constants have by default a 'static lifetime

---

src/multi.rs
src/pb.rs

```
warning: comparison to empty slice
--> src/multi.rs:249:23
|
249 |                 done: s == "",
|                       ^^^^^^^ help: using `is_empty` is clearer and more explicit: `s.is_empty()`
|
= note: `#[warn(clippy::comparison_to_empty)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#comparison_to_empty
warning: comparison to empty slice
--> src/pb.rs:218:25
|
218 |             .filter(|x| x != "")
|                         ^^^^^^^ help: using `!is_empty` is clearer and more explicit: `!x.is_empty()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#comparison_to_empty
```

Fix clippy warnings: comparison to empty slice

---

src/pb.rs

```
warning: useless use of `format!`
--> src/pb.rs:358:32
|
358 |             prefix = prefix + &format!("{}", self.message);
|                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using `.to_string()`: `self.message.to_string()`
|
= note: `#[warn(clippy::useless_format)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_format
warning: useless use of `format!`
--> src/pb.rs:440:23
|
440 |         let mut out = format!("{}", s);
|                       ^^^^^^^^^^^^^^^^ help: consider using `.to_string()`: `s.to_string()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_format
```

Fix clippy warnings: useless use of `format!`

---

src/lib.rs
src/multi.rs
src/pb.rs

Fix several warnings about redundant field names like the one below:
```
warning: redundant field names in struct initialization
--> src/multi.rs:85:17
|
85 |                 handle: handle,
|                 ^^^^^^^^^^^^^^ help: replace it with: `handle`
|
= note: `#[warn(clippy::redundant_field_names)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names
```

Fix clippy warnings: redundant field names in struct initialization

---

src/tty/windows.rs

Building on Windows was broken by 5ee1f9c49e27050390688733f7ce962cbc681529 (I think); extern crate statements were removed, but uses were only adjusted for unix, not Windows

Fix building on Windows

---

src/multi.rs
src/pb.rs

This should return the number of bytes written, which as implemented is the whole buffer.
Without this, the default `write_all` implementation won't work correctly, which is a problem with
c520a21acb3733036d77e273db09981ff8093df1.

Fix return value of `Write::write` impl for `Pipe`
